### ISSUE TITLE
SVG with XML declaration is identified as XML

### ISSUE THREAD

**Issue by TomiTakussaari** [dimapaloskin/detect-file-type#22]
This is somewhat similar case as https://github.com/dimapaloskin/detect-file-type/issues/21

So we have tool that allows users to upload images, and we use this library to initially identify those files as images.

Some of our users tried to upload some SVGs that had XML declaration in them, and those files were then rejected because they did not look like images.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg  ...svg stuff.../></svg>
```
Well, it is XML, but it is also SVG.

As custom functions and added signatures are tested only if built-in signatures do not produce match,  I could not fix this issue by using those methods.

Also, currently XML check is before SVG check in signatures.json, so this kind of SVG is always detected as XML.

I believe this could be made to work by first moving SVG check before XML, and then making SVG check contain handling for XML-declaration, if this is how this library should work?

**Comment by danielgindi** [comment]
But much more simpler than the docx issue :-)
